# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1muwwoMvIK09_iY4dYc1aIaw-CS2LByU6
"""

print ("Введите два целых числа: ")
a = input()
b = a.split (",")
if b[0]<b[1] :
  for i in range(int(b[0]),int(b[1])+1):
     print(i, end=" ")
if b[0]>b[1] :
  for i in range(int(b[0]),int(b[1])-1,-1):
     print(i, end=" ")