# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jgmAaaRgif2q9CcN2pW8EfkhZeKCtvp8
"""

print ("Введите два четырёхзначных числа: ")
a = int(input())
b = int(input())
for i in range(a, b+1):
    a1 = i // 1000
    a2 = i // 100 % 10
    a3 = i // 10 % 10
    a4 = i % 10
    if ((a1 == a4) and (a2 == a3)):
        print(i, end=" ")