# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JiyQmAQpp1PxEzkfw8PMvGBPAI61NiDw
"""

print ("Введите число: ")
a = int(input())
ishodnoe = a
check = 0
while (a>0):
  a1 = a % 10
  check = check*10 + a1
  a = a // 10
if (ishodnoe == check):
  print ("Палиндром")
else:
  print ("Не палиндром")