# -*- coding: utf-8 -*-
"""t2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlfHLrJJ6VVE-27yMsy9eoDq9B8XAxrm
"""

print ("Введите целое натуральное число: ")
n = int(input())
def my_div(n):
  nd=n
  for i in range(2,n//2+1):
    if n%i==0:
      nd=i
  return nd
print ("Наибольший делитель:", my_div(n))