# -*- coding: utf-8 -*-
"""t3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlfHLrJJ6VVE-27yMsy9eoDq9B8XAxrm
"""

print ("Введите два целых числа: ")
a,b = int(input()),int(input())
def my_sum(a,b):
  a=a+1
  b=b-1
  if b>0:
    return my_sum(a,b)
  else:
    return a
print ("Сумма чисел: ", my_sum(a,b))