# -*- coding: utf-8 -*-
"""t4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlfHLrJJ6VVE-27yMsy9eoDq9B8XAxrm
"""

print ("Введите два целых натуральных числа: ")
a,n = int(input()),int(input())
def my_power(a,n):
  if (n==1):
    return a
  else:
    return (a*my_power(a,n-1))
print ("Возведённое в степень число: ", my_power(a,n))