# -*- coding: utf-8 -*-
"""t5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RlfHLrJJ6VVE-27yMsy9eoDq9B8XAxrm
"""

xx = ['Makar Sidorov 19','Maria Kuznetsova 20','Reter Petrov 21', 'Ivan Ivanov 23']
print(sorted(xx))
print(sorted(xx, key = lambda x: int(x[-2:])))
print(xx[0])